// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// The Prisma CLI runs as its own process, outside the Nest app entirely, so
// it never sees ConfigModule's env loading -- it needs its own. Defaults to
// development since that's what you're running migrations/seed against
// from your own machine; set NODE_ENV explicitly to target another env's DB.
dotenv.config({ path: `.env.${process.env.NODE_ENV ?? "development"}` });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'node_modules/.bin/tsx prisma/seed.ts',
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
